name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'docs-source/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      ruby-version: 2.6.8

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-${{ runner.os }}-${{ env.ruby-version }}-
            gems-${{ runner.os }}-

      - run: bundle config set deployment 'true'
      - name: bundle install
        run: |
          cd docs-source
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec middleman build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-source/build
          publish_branch: release-api-docs